import type { MapDef, MapId, RosterEntry } from './types';

// 16x16, 180deg-rotationally symmetric, all walls 2 tiles thick.
const STANDARD_TERRAIN = `
................
................
........##......
........##......
........##......
....##..........
....##..........
....##..........
..........##....
..........##....
..........##....
......##........
......##........
......##........
................
................
`;

// Order matches the original ASCII grid's row-major reading order (top to
// bottom, left to right), so unit ids come out identical to before the
// terrain/roster split — this is load-bearing for anything that references
// a unit by id (e.g. a saved game's action log).
const STANDARD_ROSTER: readonly RosterEntry[] = [
  { type: 'melee', owner: 0, pos: { x: 2, y: 0 } },
  { type: 'ranged', owner: 0, pos: { x: 4, y: 0 } },
  { type: 'melee', owner: 0, pos: { x: 1, y: 1 } },
  { type: 'melee', owner: 0, pos: { x: 0, y: 2 } },
  { type: 'ranged', owner: 0, pos: { x: 1, y: 3 } },
  { type: 'ranged', owner: 1, pos: { x: 14, y: 12 } },
  { type: 'melee', owner: 1, pos: { x: 15, y: 13 } },
  { type: 'melee', owner: 1, pos: { x: 14, y: 14 } },
  { type: 'ranged', owner: 1, pos: { x: 11, y: 15 } },
  { type: 'melee', owner: 1, pos: { x: 13, y: 15 } },
];

export const MAP_STANDARD_ID: MapId = 'standard';

export const MAP_STANDARD: MapDef = {
  id: MAP_STANDARD_ID,
  terrain: STANDARD_TERRAIN,
  roster: STANDARD_ROSTER,
};

// 20x16, deliberately NOT 180deg-rotationally symmetric. A vertical water
// strait splits a west landmass (Player 0) from an east landmass (Player 1);
// row 11 is the only row that is land end-to-end, so it's the single
// crossing point a land unit can path through. Two rough tiles are included
// so the mechanic is exercised in real play, not just test fixtures.
const NORTHERN_NORWAY_TERRAIN = `
......wwwwwww.......
.......wwwww........
.....~..wwww........
........wwwww.......
.......wwwwww.......
.......wwwwwww......
......wwwwwwww......
......wwwwwww.......
.......wwwwww.......
........wwww........
........wwww........
....................
........wwww........
.......wwwwww.~.....
......wwwwwww.......
.....wwwwwwwww......
`;

// Reading order gives the ids `movement.ts`/`ai.ts` and the merge tests key
// off: 0,1 are the adjacent P0 melee pair, 2..9 alternate roughly by row.
const NORTHERN_NORWAY_ROSTER: readonly RosterEntry[] = [
  { type: 'melee', owner: 0, pos: { x: 2, y: 3 } },
  { type: 'melee', owner: 0, pos: { x: 3, y: 4 } },
  { type: 'melee', owner: 1, pos: { x: 17, y: 4 } },
  { type: 'ranged', owner: 0, pos: { x: 4, y: 5 } },
  { type: 'ranged', owner: 1, pos: { x: 15, y: 6 } },
  { type: 'melee', owner: 1, pos: { x: 16, y: 8 } },
  { type: 'ranged', owner: 0, pos: { x: 4, y: 9 } },
  { type: 'ranged', owner: 1, pos: { x: 15, y: 10 } },
  { type: 'melee', owner: 0, pos: { x: 2, y: 12 } },
  { type: 'melee', owner: 1, pos: { x: 17, y: 12 } },
];

export const MAP_NORTHERN_NORWAY_ID: MapId = 'northern-norway';

export const MAP_NORTHERN_NORWAY: MapDef = {
  id: MAP_NORTHERN_NORWAY_ID,
  terrain: NORTHERN_NORWAY_TERRAIN,
  roster: NORTHERN_NORWAY_ROSTER,
};

const REGISTRY: Record<MapId, MapDef> = {
  [MAP_STANDARD_ID]: MAP_STANDARD,
  [MAP_NORTHERN_NORWAY_ID]: MAP_NORTHERN_NORWAY,
};

export function getMapDef(id: MapId): MapDef {
  const def = REGISTRY[id];
  if (!def) throw new Error(`getMapDef: unknown map id '${id}'`);
  return def;
}
