// 16x16, 180deg-rotationally symmetric, all walls 2 tiles thick.
export const MAP_STANDARD = `
..m.r...........
.m..............
m.......##......
.r......##......
........##......
....##..........
....##..........
....##..........
..........##....
..........##....
..........##....
......##........
......##......R.
......##.......M
..............M.
...........R.M..
`;

// 20x16, deliberately NOT 180deg-rotationally symmetric. A vertical water
// strait splits a west landmass (Player 0) from an east landmass (Player 1);
// row 11 is the only row that is land end-to-end, so it's the single
// crossing point a land unit can path through. Two rough tiles are included
// so the mechanic is exercised in real play, not just test fixtures.
export const MAP_NORTHERN_NORWAY = `
......wwwwwww.......
.......wwwww........
.....~..wwww........
..m.....wwwww.......
...m...wwwwww....M..
....r..wwwwwww......
......wwwwwwww.R....
......wwwwwww.......
.......wwwwww...M...
....r...wwww........
........wwww...R....
....................
..m.....wwww.....M..
.......wwwwww.~.....
......wwwwwww.......
.....wwwwwwwww......
`;
